 Reading the CSV

In [2]:
import pandas as pd

In [3]:
df1 = pd.read_csv('Environment_Impact_of_Food_Production.csv') # emissions table
df1.columns

Index(['Food product', 'Land use change', 'Animal Feed', 'Farm', 'Processing',
       'Transport', 'Packging', 'Retail', 'Total_emissions',
       'Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal)',
       'Eutrophying emissions per kilogram (gPO₄eq per kilogram)',
       'Eutrophying emissions per 100g protein (gPO₄eq per 100 grams protein)',
       'Freshwater withdrawals per 1000kcal (liters per 1000kcal)',
       'Freshwater withdrawals per 100g protein (liters per 100g protein)',
       'Freshwater withdrawals per kilogram (liters per kilogram)',
       'Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal)',
       'Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein)',
       'Land use per 1000kcal (m² per 1000kcal)',
       'Land use per kilogram (m² per kilogram)',
       'Land use per 100g protein (m² per 100g protein)',
       'Scarcity-weighted water use per kilogram (liters per kilogram)',
       'Scarcity-weighted water use per 100g protein (liters per 100g protein)',
       'Scarcity-weighted water use per 1000kcal (liters per 1000 kilocalories)'],
      dtype='object')

In [4]:
df1['Food product'].unique()

array(['Wheat & Rye (Bread)', 'Maize (Meal)', 'Barley (Beer)', 'Oatmeal',
       'Rice', 'Potatoes', 'Cassava', 'Cane Sugar', 'Beet Sugar',
       'Other Pulses', 'Peas', 'Nuts', 'Groundnuts', 'Soymilk', 'Tofu',
       'Soybean Oil', 'Palm Oil', 'Sunflower Oil', 'Rapeseed Oil',
       'Olive Oil', 'Tomatoes', 'Onions & Leeks', 'Root Vegetables',
       'Brassicas', 'Other Vegetables', 'Citrus Fruit', 'Bananas',
       'Apples', 'Berries & Grapes', 'Wine', 'Other Fruit', 'Coffee',
       'Dark Chocolate', 'Beef (beef herd)', 'Beef (dairy herd)',
       'Lamb & Mutton', 'Pig Meat', 'Poultry Meat', 'Milk', 'Cheese',
       'Eggs', 'Fish (farmed)', 'Shrimps (farmed)'], dtype=object)

In [5]:
df1.columns

Index(['Food product', 'Land use change', 'Animal Feed', 'Farm', 'Processing',
       'Transport', 'Packging', 'Retail', 'Total_emissions',
       'Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal)',
       'Eutrophying emissions per kilogram (gPO₄eq per kilogram)',
       'Eutrophying emissions per 100g protein (gPO₄eq per 100 grams protein)',
       'Freshwater withdrawals per 1000kcal (liters per 1000kcal)',
       'Freshwater withdrawals per 100g protein (liters per 100g protein)',
       'Freshwater withdrawals per kilogram (liters per kilogram)',
       'Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal)',
       'Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein)',
       'Land use per 1000kcal (m² per 1000kcal)',
       'Land use per kilogram (m² per kilogram)',
       'Land use per 100g protein (m² per 100g protein)',
       'Scarcity-weighted water use per kilogram (liters per kilogram)',
       'Scarcity-weighted water use per 100g protein (liters per 100g protein)',
       'Scarcity-weighted water use per 1000kcal (liters per 1000 kilocalories)'],
      dtype='object')

In [6]:
df2 = pd.read_csv('Who_eats_the_food_we_grow.csv', encoding='ISO-8859-1') # the food we grow table
df2.head(10)

,Area Abbreviation,Area Code,Area,Item Code,Item,Element Code,Element,Unit,latitude,longitude,...,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013
0,AFG,2,Afghanistan,2511,Wheat and products,5142,Food,1000 tonnes,33.94,67.71,...,3249.0,3486.0,3704.0,4164.0,4252.0,4538.0,4605.0,4711.0,4810,4895
1,AFG,2,Afghanistan,2805,Rice (Milled Equivalent),5142,Food,1000 tonnes,33.94,67.71,...,419.0,445.0,546.0,455.0,490.0,415.0,442.0,476.0,425,422
2,AFG,2,Afghanistan,2513,Barley and products,5521,Feed,1000 tonnes,33.94,67.71,...,58.0,236.0,262.0,263.0,230.0,379.0,315.0,203.0,367,360
3,AFG,2,Afghanistan,2513,Barley and products,5142,Food,1000 tonnes,33.94,67.71,...,185.0,43.0,44.0,48.0,62.0,55.0,60.0,72.0,78,89
4,AFG,2,Afghanistan,2514,Maize and products,5521,Feed,1000 tonnes,33.94,67.71,...,120.0,208.0,233.0,249.0,247.0,195.0,178.0,191.0,200,200
5,AFG,2,Afghanistan,2514,Maize and products,5142,Food,1000 tonnes,33.94,67.71,...,231.0,67.0,82.0,67.0,69.0,71.0,82.0,73.0,77,76
6,AFG,2,Afghanistan,2517,Millet and products,5142,Food,1000 tonnes,33.94,67.71,...,15.0,21.0,11.0,19.0,21.0,18.0,14.0,14.0,14,12
7,AFG,2,Afghanistan,2520,"Cereals, Other",5142,Food,1000 tonnes,33.94,67.71,...,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
8,AFG,2,Afghanistan,2531,Potatoes and products,5142,Food,1000 tonnes,33.94,67.71,...,276.0,294.0,294.0,260.0,242.0,250.0,192.0,169.0,196,230
9,AFG,2,Afghanistan,2536,Sugar cane,5521,Feed,1000 tonnes,33.94,67.71,...,50.0,29.0,61.0,65.0,54.0,114.0,83.0,83.0,69,81

In [7]:
df2.columns

Index(['Area Abbreviation', 'Area Code', 'Area', 'Item Code', 'Item',
       'Element Code', 'Element', 'Unit', 'latitude', 'longitude', 'Y1961',
       'Y1962', 'Y1963', 'Y1964', 'Y1965', 'Y1966', 'Y1967', 'Y1968', 'Y1969',
       'Y1970', 'Y1971', 'Y1972', 'Y1973', 'Y1974', 'Y1975', 'Y1976', 'Y1977',
       'Y1978', 'Y1979', 'Y1980', 'Y1981', 'Y1982', 'Y1983', 'Y1984', 'Y1985',
       'Y1986', 'Y1987', 'Y1988', 'Y1989', 'Y1990', 'Y1991', 'Y1992', 'Y1993',
       'Y1994', 'Y1995', 'Y1996', 'Y1997', 'Y1998', 'Y1999', 'Y2000', 'Y2001',
       'Y2002', 'Y2003', 'Y2004', 'Y2005', 'Y2006', 'Y2007', 'Y2008', 'Y2009',
       'Y2010', 'Y2011', 'Y2012', 'Y2013'],
      dtype='object')

In [8]:
df2['Item'].unique()

array(['Wheat and products', 'Rice (Milled Equivalent)',
       'Barley and products', 'Maize and products', 'Millet and products',
       'Cereals, Other', 'Potatoes and products', 'Sugar cane',
       'Sugar beet', 'Sugar (Raw Equivalent)', 'Sweeteners, Other',
       'Honey', 'Pulses, Other and products', 'Nuts and products',
       'Coconuts - Incl Copra', 'Sesame seed',
       'Olives (including preserved)', 'Soyabean Oil', 'Groundnut Oil',
       'Sunflowerseed Oil', 'Rape and Mustard Oil', 'Cottonseed Oil',
       'Palm Oil', 'Sesameseed Oil', 'Olive Oil', 'Oilcrops Oil, Other',
       'Tomatoes and products', 'Vegetables, Other',
       'Oranges, Mandarines', 'Citrus, Other', 'Bananas',
       'Apples and products', 'Pineapples and products', 'Dates',
       'Grapes and products (excl wine)', 'Fruits, Other',
       'Coffee and products', 'Cocoa Beans and products',
       'Tea (including mate)', 'Pepper', 'Spices, Other', 'Wine', 'Beer',
       'Beverages, Alcoholic', 'Bovine Meat', 'Mutton & Goat Meat',
       'Poultry Meat', 'Meat, Other', 'Offals, Edible', 'Butter, Ghee',
       'Cream', 'Fats, Animals, Raw', 'Eggs', 'Milk - Excluding Butter',
       'Freshwater Fish', 'Infant food', 'Cereals - Excluding Beer',
       'Starchy Roots', 'Sugar Crops', 'Sugar & Sweeteners', 'Pulses',
       'Treenuts', 'Oilcrops', 'Vegetable Oils', 'Vegetables',
       'Fruits - Excluding Wine', 'Stimulants', 'Spices',
       'Alcoholic Beverages', 'Meat', 'Offals', 'Animal fats',
       'Fish, Seafood', 'Miscellaneous', 'Rye and products', 'Oats',
       'Sorghum and products', 'Cassava and products', 'Sweet potatoes',
       'Roots, Other', 'Beans', 'Peas', 'Soyabeans',
       'Groundnuts (Shelled Eq)', 'Rape and Mustardseed',
       'Oilcrops, Other', 'Maize Germ Oil', 'Onions',
       'Lemons, Limes and products', 'Grapefruit and products',
       'Plantains', 'Pimento', 'Beverages, Fermented', 'Pigmeat',
       'Fish, Body Oil', 'Fish, Liver Oil', 'Demersal Fish',
       'Pelagic Fish', 'Marine Fish, Other', 'Crustaceans', 'Cephalopods',
       'Molluscs, Other', 'Aquatic Animals, Others', 'Aquatic Plants',
       'Aquatic Products, Other', 'Palm kernels', 'Coconut Oil', 'Cloves',
       'Palmkernel Oil', 'Yams', 'Sunflower seed', 'Cottonseed',
       'Sugar non-centrifugal', 'Ricebran Oil', 'Meat, Aquatic Mammals'],
      dtype=object)

In [9]:
df1.drop(columns=['Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal)',
       'Eutrophying emissions per kilogram (gPO₄eq per kilogram)',
       'Eutrophying emissions per 100g protein (gPO₄eq per 100 grams protein)',
       'Freshwater withdrawals per 1000kcal (liters per 1000kcal)',
       'Freshwater withdrawals per 100g protein (liters per 100g protein)',
       'Freshwater withdrawals per kilogram (liters per kilogram)',
       'Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal)',
       'Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein)',
       'Land use per 1000kcal (m² per 1000kcal)',
       'Land use per kilogram (m² per kilogram)',
       'Land use per 100g protein (m² per 100g protein)',
       'Scarcity-weighted water use per kilogram (liters per kilogram)',
       'Scarcity-weighted water use per 100g protein (liters per 100g protein)',
       'Scarcity-weighted water use per 1000kcal (liters per 1000 kilocalories)'])

,Food product,Land use change,Animal Feed,Farm,Processing,Transport,Packging,Retail,Total_emissions
0,Wheat & Rye (Bread),0.1,0.0,0.8,0.2,0.1,0.1,0.1,1.4
1,Maize (Meal),0.3,0.0,0.5,0.1,0.1,0.1,0.0,1.1
2,Barley (Beer),0.0,0.0,0.2,0.1,0.0,0.5,0.3,1.1
3,Oatmeal,0.0,0.0,1.4,0.0,0.1,0.1,0.0,1.6
4,Rice,0.0,0.0,3.6,0.1,0.1,0.1,0.1,4.0
5,Potatoes,0.0,0.0,0.2,0.0,0.1,0.0,0.0,0.3
6,Cassava,0.6,0.0,0.2,0.0,0.1,0.0,0.0,0.9
7,Cane Sugar,1.2,0.0,0.5,0.0,0.8,0.1,0.0,2.6
8,Beet Sugar,0.0,0.0,0.5,0.2,0.6,0.1,0.0,1.4
9,Other Pulses,0.0,0.0,1.1,0.0,0.1,0.4,0.0,1.6
10,Peas,0.0,0.0,0.7,0.0,0.1,0.0,0.0,0.8
11,Nuts,-2.1,0.0,2.1,0.0,0.1,0.1,0.0,0.2
12,Groundnuts,0.4,0.0,1.4,0.4,0.1,0.1,0.0,2.4
13,Soymilk,0.2,0.0,0.1,0.2,0.1,0.1,0.3,1.0
14,Tofu,1.0,0.0,0.5,0.8,0.2,0.2,0.3,3.0
15,Soybean Oil,3.1,0.0,1.5,0.3,0.3,0.8,0.0,6.0
16,Palm Oil,3.1,0.0,2.1,1.3,0.2,0.9,0.0,7.6
17,Sunflower Oil,0.1,0.0,2.1,0.2,0.2,0.9,0.0,3.5
18,Rapeseed Oil,0.2,0.0,2.3,0.2,0.2,0.8,0.0,3.7
19,Olive Oil,-0.4,0.0,4.3,0.7,0.5,0.9,0.0,6.0
20,Tomatoes,0.4,0.0,0.7,0.0,0.2,0.1,0.0,1.4
21,Onions & Leeks,0.0,0.0,0.2,0.0,0.1,0.0,0.0,0.3
22,Root Vegetables,0.0,0.0,0.2,0.0,0.1,0.0,0.0,0.3
23,Brassicas,0.0,0.0,0.3,0.0,0.1,0.0,0.0,0.4
24,Other Vegetables,0.0,0.0,0.2,0.1,0.2,0.0,0.0,0.5
25,Citrus Fruit,-0.1,0.0,0.3,0.0,0.1,0.0,0.0,0.3
26,Bananas,0.0,0.0,0.3,0.1,0.3,0.1,0.0,0.8
27,Apples,0.0,0.0,0.2,0.0,0.1,0.0,0.0,0.3
28,Berries & Grapes,0.0,0.0,0.7,0.0,0.2,0.2,0.0,1.1
29,Wine,-0.1,0.0,0.6,0.1,0.1,0.7,0.0,1.4
30,Other Fruit,0.1,0.0,0.4,0.0,0.2,0.0,0.0,0.7
31,Coffee,3.7,0.0,10.4,0.6,0.1,1.6,0.1,16.5
32,Dark Chocolate,14.3,0.0,3.7,0.2,0.1,0.4,0.0,18.7
33,Beef (beef herd),16.3,1.9,39.4,1.3,0.3,0.2,0.2,59.6
34,Beef (dairy herd),0.9,2.5,15.7,1.1,0.4,0.3,0.2,21.1
35,Lamb & Mutton,0.5,2.4,19.5,1.1,0.5,0.3,0.2,24.5
36,Pig Meat,1.5,2.9,1.7,0.3,0.3,0.3,0.2,7.2
37,Poultry Meat,2.5,1.8,0.7,0.4,0.3,0.2,0.2,6.1
38,Milk,0.5,0.2,1.5,0.1,0.1,0.1,0.3,2.8
39,Cheese,4.5,2.3,13.1,0.7,0.1,0.2,0.3,21.2
40,Eggs,0.7,2.2,1.3,0.0,0.1,0.2,0.0,4.5
41,Fish (farmed),0.5,0.8,3.6,0.0,0.1,0.1,0.0,5.1
42,Shrimps (farmed),0.2,2.5,8.4,0.0,0.2,0.3,0.2,11.8

In [11]:
df2.columns
df2.drop(columns=['Element Code', 'Element', 'Unit', 'latitude', 'longitude', 'Y1961',
       'Y1962', 'Y1963', 'Y1964', 'Y1965', 'Y1966', 'Y1967', 'Y1968', 'Y1969',
       'Y1970', 'Y1971', 'Y1972', 'Y1973', 'Y1974', 'Y1975', 'Y1976', 'Y1977',
       'Y1978', 'Y1979', 'Y1980', 'Y1981', 'Y1982', 'Y1983', 'Y1984', 'Y1985',
       'Y1986', 'Y1987', 'Y1988', 'Y1989', 'Y1990', 'Y1991', 'Y1992', 'Y1993',
       'Y1994', 'Y1995', 'Y1996', 'Y1997', 'Y1998', 'Y1999', 'Y2000', 'Y2001',
       'Y2002', 'Y2003', 'Y2004', 'Y2005', 'Y2006', 'Y2007', 'Y2008', 'Y2009',
       'Y2010', 'Y2011', 'Y2012', 'Y2013'])

,Area Abbreviation,Area Code,Area,Item Code,Item
0,AFG,2,Afghanistan,2511,Wheat and products
1,AFG,2,Afghanistan,2805,Rice (Milled Equivalent)
2,AFG,2,Afghanistan,2513,Barley and products
3,AFG,2,Afghanistan,2513,Barley and products
4,AFG,2,Afghanistan,2514,Maize and products
...,...,...,...,...,...
21472,ZWE,181,Zimbabwe,2948,Milk - Excluding Butter
21473,ZWE,181,Zimbabwe,2960,"Fish, Seafood"
21474,ZWE,181,Zimbabwe,2960,"Fish, Seafood"
21475,ZWE,181,Zimbabwe,2961,"Aquatic Products, Other"
21476,ZWE,181,Zimbabwe,2928,Miscellaneous